repos:
  # 🔹 Valida o formato da mensagem do commit com o Commitizen
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0  # Use a última versão disponível
    hooks:
      - id: commitizen

  # 🔹 Remove espaços em branco desnecessários
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace

  # 🔹 Garante que os arquivos possuem uma linha final
      - id: end-of-file-fixer

  # 🔹 Reorganiza os imports automaticamente
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports

  # 🔹 Formata o código com Black
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: ["--line-length=88"]

  # 🔹 Garante que os arquivos do Python tenham encoding correto
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  # 🔹 Analisa o código em busca de erros
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
