name: Executar Testes Unit치rios

on:
  push:  # Roda em qualquer push
  pull_request:
    branches:
      -main
      -develop

jobs:
  test:
    runs-on: ubuntu-latest  # Usa o Ubuntu mais recente

    steps:
      - name: 游닌 Clonar reposit칩rio
        uses: actions/checkout@v4

      - name: 游냀 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Altere se necess치rio

      - name: 游닍 Instalar Poetry
        run: pip install poetry

      - name: 游닍 Instalar depend칡ncias do projeto
        run: poetry install --no-interaction --no-root

      - name: 游댌 Rodar testes com pytest
        run: poetry run pytest --disable-warnings --maxfail=1